[package]
name = "pwbox"
version = "0.1.0"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]

[dependencies]
rand_core = "0.3.0"
clear_on_drop = "0.2.3"
smallvec = "0.6.6"
failure = "0.1.3"
failure_derive = "0.1.3"
# serialization-related dependencies
hex = "0.3.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
# crypto backends
exonum_sodiumoxide = { version = "0.0.20", optional = true }
rust-crypto = { version = "0.2.36", optional = true }

[dev-dependencies]
rand = "0.6.1"
assert_matches = "1.3.0"
toml = "0.4.9"
criterion = "0.2.5"

[features]
default = ["exonum_sodiumoxide", "rust-crypto"]

[[bench]]
name = "eq"
harness = false
path = "benches/eq.rs"
